AWSTemplateFormatVersion: "2010-09-09"
Description: Fixed CloudFormation Template - EC2 Instance with Security Group

Parameters:
  AmiId:
    Type: String
    Description: Amazon Linux 2 AMI ID (valid public AMI)
    Default: ami-0c55f5e3c6b0e9b8b  # Example for us-east-1, update per your region

  InstanceType:
    Type: String
    Default: t2.micro
    Description: EC2 instance type

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The VPC ID where the security group and instance will be created

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to SSH into the instance
    Default: my-keypair

Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP access
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0  # ✅ Fixed invalid CIDR block
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: MyFixedSecurityGroup

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AmiId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: FixedEC2Instance

Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref MyEC2Instance

  InstancePublicIP:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt MyEC2Instance.PublicIp
